# Generated by Django 3.0.7 on 2020-06-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20200613_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='research',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
