# Generated by Django 3.0.7 on 2020-06-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20200613_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='media')),
            ],
            options={
                'verbose_name': 'Хууль',
                'verbose_name_plural': 'Хууль тогтоомж',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='LawCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Law Category ')),
            ],
            options={
                'verbose_name': 'Хууль бүлэг',
                'verbose_name_plural': 'Хууль тогтоомж бүлэг',
                'ordering': ['title'],
            },
        ),
    ]
