# Generated by Django 2.2 on 2020-07-03 05:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20200618_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='law',
            options={'ordering': ['title'], 'verbose_name': 'Хууль тогтоомж', 'verbose_name_plural': 'Хууль тогтоомж'},
        ),
        migrations.AlterField(
            model_name='law',
            name='category',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Law', to='research.LawCategory', verbose_name='Хууль бүлэг'),
        ),
        migrations.AlterField(
            model_name='law',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Хэзээ үүсгэсэн'),
        ),
        migrations.AlterField(
            model_name='law',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_file', verbose_name='Файл хийх'),
        ),
        migrations.AlterField(
            model_name='law',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Гарчиг'),
        ),
        migrations.AlterField(
            model_name='law',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Хэзээ засварласан'),
        ),
        migrations.AlterField(
            model_name='lawcategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Хууль тогтоомж '),
        ),
        migrations.AlterField(
            model_name='research',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Үүсгэсэн'),
        ),
        migrations.AlterField(
            model_name='research',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контэнт'),
        ),
        migrations.AlterField(
            model_name='research',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Хэзээ үүсгэсэн'),
        ),
        migrations.AlterField(
            model_name='research',
            name='image',
            field=models.ImageField(upload_to='media/research/', verbose_name='Зураг'),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Гарчиг'),
        ),
        migrations.AlterField(
            model_name='research',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Хэзээ засварласан'),
        ),
    ]
