# Generated by Django 3.0.7 on 2020-07-22 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_auto_20200703_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='law',
            options={'ordering': ['title'], 'verbose_name': 'legislation', 'verbose_name_plural': 'legislations'},
        ),
        migrations.AlterModelOptions(
            name='lawcategory',
            options={'ordering': ['title'], 'verbose_name': 'Legislation category', 'verbose_name_plural': 'legislation categorys'},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ['created_on'], 'verbose_name': 'Research', 'verbose_name_plural': 'Researchs'},
        ),
        migrations.AlterModelOptions(
            name='researchcategory',
            options={'ordering': ['title'], 'verbose_name': 'Research category', 'verbose_name_plural': 'Research categorys'},
        ),
    ]
