# Generated by Django 3.0.7 on 2020-07-22 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_auto_20200722_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='law',
            options={'ordering': ['title'], 'verbose_name': 'Хууль тогтоомж', 'verbose_name_plural': 'Хууль тогтоомж'},
        ),
        migrations.AlterModelOptions(
            name='lawcategory',
            options={'ordering': ['title'], 'verbose_name': 'Хууль тогтоомж бүлэг', 'verbose_name_plural': 'Хууль тогтоомж бүлэг'},
        ),
    ]
