# Generated by Django 3.0.7 on 2020-07-22 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_auto_20200722_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ['created_on'], 'verbose_name': 'Судалгаа', 'verbose_name_plural': 'Судалгаа'},
        ),
        migrations.AlterModelOptions(
            name='researchcategory',
            options={'ordering': ['title'], 'verbose_name': 'Судалгааны ангиллал', 'verbose_name_plural': 'Судалгааны ангиллал'},
        ),
    ]
