# Generated by Django 3.0.7 on 2020-08-03 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_auto_20200722_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='law',
            options={'ordering': ['title'], 'verbose_name': 'Legislation', 'verbose_name_plural': 'Legislations'},
        ),
        migrations.AlterModelOptions(
            name='lawcategory',
            options={'ordering': ['title'], 'verbose_name': 'Legislation category', 'verbose_name_plural': 'Legislation category'},
        ),
        migrations.AlterModelOptions(
            name='researchcategory',
            options={},
        ),
        migrations.AlterField(
            model_name='law',
            name='category',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Law', to='research.LawCategory', verbose_name='Legislation category'),
        ),
        migrations.AlterField(
            model_name='law',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='law',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_file', verbose_name='Upload file'),
        ),
        migrations.AlterField(
            model_name='law',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='law',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated on'),
        ),
    ]
