# Generated by Django 2.2 on 2020-07-03 05:08

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200701_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курс'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': ['title'], 'verbose_name': 'Сургалтын Бүлэг', 'verbose_name_plural': 'Сургалтын бүлэгүүд'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['title'], 'verbose_name': 'Хичээл', 'verbose_name_plural': 'Хичээл'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title'], 'verbose_name': 'Сэдэв', 'verbose_name_plural': 'Сэдэв'},
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='cat_images/default.jpg', upload_to='cat_images', verbose_name='Зураг'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Сурагчид'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Гарчиг'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=models.IntegerField(verbose_name='Хичээлийн байрлал'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Subject', verbose_name='Сэдэв'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=30, verbose_name=' Хичээлийн гарчиг'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_id',
            field=models.FileField(blank=True, null=True, upload_to='course_video', verbose_name='Бичлэг хийх'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Үүсгэсэн '),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Хэзээ үүсгэсэн'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image_field',
            field=models.ImageField(default='default.jpg', upload_to='kurs_images', verbose_name='Зураг оруулах'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Гарчиг'),
        ),
    ]
