# Generated by Django 2.2 on 2020-07-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200703_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(default='₮', max_length=150, verbose_name='Үнэ'),
        ),
    ]
