# Generated by Django 2.2 on 2020-07-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_file'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='course_image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='cat_images/default.png', upload_to='cat_images', verbose_name='Зураг'),
        ),
    ]
