# Generated by Django 3.0.7 on 2020-07-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200710_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': ['title'], 'verbose_name': 'Course category', 'verbose_name_plural': 'Course categories'},
        ),
    ]
