# Generated by Django 3.0.7 on 2020-07-22 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200722_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курс'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': ['title'], 'verbose_name': 'Курсын категори', 'verbose_name_plural': 'Курсын категори'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['title'], 'verbose_name': 'Хичээл', 'verbose_name_plural': 'Хичээл'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title'], 'verbose_name': 'Сэдэв', 'verbose_name_plural': 'Сэдэв'},
        ),
    ]
