# Generated by Django 3.0.7 on 2020-10-21 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_attandance'),
        ('quiz', '0003_auto_20201019_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Ангилал', 'verbose_name_plural': 'Ангилалууд'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['category'], 'verbose_name': 'Question', 'verbose_name_plural': 'Асуултууд'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Ангилал'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Category', verbose_name='Ангилал'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Category', verbose_name='Ангилал'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, help_text='Асуултын тайлбар', verbose_name='Тайлбар'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.Lesson', verbose_name='Хичээл'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_questions',
            field=models.PositiveIntegerField(blank=True, help_text='Оролт болгон дээр хариулах асуултын тоо.', null=True, verbose_name='Оруулж болох хамгын их асуултын тоо'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='random_order',
            field=models.BooleanField(default=False, help_text='Display the questions in a random order or as they are set?', verbose_name='Хамааралгүй дугаарлах'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='url',
            field=models.SlugField(help_text='Хэрэглэгчид харагдах slug', max_length=60, verbose_name='Хэрэглэгчид харагдах slug'),
        ),
    ]
