# Generated by Django 2.2 on 2020-07-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200706_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='fullname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
