# Generated by Django 2.2 on 2020-07-06 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200706_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Contact',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Холбоо барих'},
        ),
    ]
