# Generated by Django 2.2 on 2020-07-07 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_contact_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Сургалт хүссэн '},
        ),
    ]
