# Generated by Django 2.2 on 2020-07-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200707_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('Phone', models.CharField(default='', max_length=10)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Холбоо барих',
                'ordering': ['name'],
            },
        ),
    ]
