# Generated by Django 3.0.7 on 2020-07-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.FileField(upload_to='media/navigation/icon', verbose_name='Icon')),
                ('url', models.URLField(verbose_name='Url')),
                ('is_special', models.BooleanField(default='False', verbose_name='boxed')),
            ],
            options={
                'verbose_name': 'Navigation menu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DropMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent_id', models.ManyToManyField(to='website.Menu', verbose_name='Dropdown navigation child')),
            ],
        ),
    ]
