# Generated by Django 3.0.7 on 2020-07-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_special',
            field=models.BooleanField(default='True', verbose_name='boxed'),
        ),
    ]
