# Generated by Django 3.0.7 on 2020-07-23 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_menu_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['position'], 'verbose_name': 'Navigation menu'},
        ),
        migrations.RemoveField(
            model_name='dropmenu',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='dropmenu',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Menu', verbose_name='Dropdown navigation child'),
        ),
    ]
