# Generated by Django 3.0.7 on 2020-07-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='icon',
            field=models.FileField(null=True, upload_to='media/icon'),
        ),
    ]
