# Generated by Django 3.0.7 on 2020-07-23 11:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200723_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контэнт'),
        ),
    ]
