# Generated by Django 3.0.7 on 2020-07-23 12:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200723_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, null=True, upload_to='media/icon')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контэнт')),
                ('position', models.IntegerField(default='0')),
            ],
            options={
                'verbose_name': 'Mission',
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['title'], 'verbose_name': 'Mission'},
        ),
        migrations.RemoveField(
            model_name='mission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='position',
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mission content'),
        ),
    ]
