# Generated by Django 3.0.7 on 2020-07-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200723_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=550)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='vision',
            options={'ordering': ['position'], 'verbose_name': 'Vision'},
        ),
    ]
