# Generated by Django 3.0.7 on 2020-07-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_presidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidents',
            name='position',
            field=models.IntegerField(default='0'),
        ),
    ]
