# Generated by Django 3.0.7 on 2020-07-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200724_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/partner/')),
                ('position', models.IntegerField(default='0')),
            ],
            options={
                'verbose_name': 'partner',
                'ordering': ['position'],
            },
        ),
    ]
