# Generated by Django 3.0.7 on 2020-07-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20200724_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='post_image',
        ),
        migrations.AddField(
            model_name='partner',
            name='image',
            field=models.FileField(default=0, upload_to='media/website/presidents/'),
            preserve_default=False,
        ),
    ]
