# Generated by Django 3.0.7 on 2020-07-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20200724_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutpagemission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('icon', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'aboutoage',
            },
        ),
    ]
