# Generated by Django 3.0.7 on 2020-07-24 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_aboutpagemission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagemission',
            options={'verbose_name': 'aboutpagemission'},
        ),
    ]
