# Generated by Django 3.0.7 on 2020-10-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20200724_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(max_length=255, verbose_name='Carousel image alt text')),
                ('image', models.ImageField(upload_to='media/Carousel')),
                ('title', models.CharField(max_length=255, verbose_name='Carousel Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Carousel',
            },
        ),
    ]
