# Generated by Django 3.0.7 on 2020-10-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Carousel Title'),
        ),
    ]
