# Generated by Django 3.0.7 on 2020-10-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20201021_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='position',
            field=models.IntegerField(default=0, help_text='Оруулсан зураг хэдэд байрлахыг зааж өгнө '),
            preserve_default=False,
        ),
    ]
