# Generated by Django 3.0.7 on 2020-10-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_carousel_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['position'], 'verbose_name': 'Carousel'},
        ),
    ]
