# Generated by Django 3.0.7 on 2020-06-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
