# Generated by Django 3.0.7 on 2020-06-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cate_type',
            field=models.CharField(choices=[('news', 'News'), ('sport', 'Sport')], default='news', max_length=255),
        ),
    ]
