# Generated by Django 3.0.7 on 2020-06-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200613_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_type',
            field=models.CharField(choices=[('news', 'News'), ('sport', 'Sport'), ('research', 'Research')], default='news', max_length=255),
        ),
    ]
