# Generated by Django 3.0.7 on 2020-06-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200613_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
