# Generated by Django 3.0.7 on 2020-06-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200613_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
    ]
