# Generated by Django 3.0.7 on 2020-06-22 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200615_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_on'], 'verbose_name': 'Нийтлэл', 'verbose_name_plural': 'Нийтлэлүүд'},
        ),
    ]
