# Generated by Django 2.2 on 2020-07-03 05:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200622_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Мэдээний бүлэг', 'verbose_name_plural': 'Мэдээний бүлэгүүд'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Гарчиг'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Үүсгэсэн'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Хэзээ үүссэн'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='media/news/', verbose_name='Зураг'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Гарчиг'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Хэзээ засварласан'),
        ),
    ]
