# Generated by Django 3.0.7 on 2020-07-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200710_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'News category', 'verbose_name_plural': 'News categories'},
        ),
    ]
