# Generated by Django 3.0.7 on 2020-07-22 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200722_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Мэдээ ангиллал', 'verbose_name_plural': 'Мэдээ ангиллал'},
        ),
    ]
