# Generated by Django 3.0.7 on 2020-10-13 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20201013_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
    ]
