# Generated by Django 3.0.7 on 2020-10-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestion',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('content', 'Content'), ('none', 'None')], default='Content', help_text='The order in which multichoice                     answer options are displayed                     to the user', max_length=30, null=True, verbose_name='Answer Order'),
        ),
    ]
